### ISSUE TITLE
Output files should follow BIDS-like naming convention

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#133]
The output filenames can be changed to have key-value pairs, much like BIDS. We can also take some cues from the [PALM](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/PALM) conventions.

EDIT 2020/08/01: TS adding a checklist.

- [x] Implement naming convention for output files. (#224)
- [x] Document naming convention in docs. (#333)
- [x] Create flat json describing the convention, based on the PyBIDS config files. (#338)

**Comment by mriedel56** [comment]
Maybe there could be associated JSON files as well, with key-value pairs such as: thresholding procedure (cFWE, vFWE, TFCE), corresponding significance levels, minimum and maximum ALE/Z statistics, cluster sizes (maybe just the size needed for significance, or all and each ones p-value?). I'm sure there is a ton of other stuff that could be included too

**Comment by tsalo** [comment]
I think that's doable. That would probably fall under the BIDS Models specification (or something like it). IIRC, a group talked about this a bit at the OHBM hackathon, although I can't remember what the conclusion was (i.e., if we would use BIDS Models or create a new specification).

**Comment by tyarkoni** [comment]
It's come up before, and I don't recall there being a general consensus as to whether the BIDS-StatsModel spec should say something about file names, or if that should go somewhere else. Personally I think it probably makes sense to ultimately include that in the BIDS-SM spec, but it could start off elsewhere.

For now I think it's fine if you make executive decisions that work for you in NiMARE, as long as they respect the general BIDS naming conventions. But maybe you can store all key names you use, and closed-vocab values, in a flat JSON file, so that they can be easily modified later (basically something analogous to the entity config files in PyBIDS).

**Comment by tsalo** [comment]
As of #224, the pattern is `[value]_desc-[description]_level-[cluster|voxel]_corr-[FWE|FDR]_method-[method]`. We can adapt further, but I think it's a good start.
