### ISSUE TITLE
p-values are 1 when using FWECorrector with certain meta-analysis algo & kernel combinations

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#355]
related to #352 and #353 

The "logp_level-voxel_corr-FWE_method-montecarlo" should not contain log-p-values of 0's and the transformation of the map to p-values should not contain p-values of 1's.

However, the following combinations of meta-analysis algos and kernels display this behavior:
- [ ] meta: ALE, kernel: ALEKernel
- [ ] meta: ALE, kernel: MKDAKernel
- [ ] meta: MKDADensity, kernel: ALEKernel
- [ ] meta: MKDADensity, kernel: MKDAKernel
- [ ] meta: MKDADensity, kernel: KDAKernel
- [ ] meta: KDA, kernel: MKDAKernel

Currently, my test is including all voxels not just the voxels within the mask, so I do not know how the voxels outside the mask should be represented (perhaps a 1 is reasonable for voxels outside of the mask, but at least for the ALE + ALEKernel, even when masked I found p-values equal to 1).

**Comment by tsalo** [comment]
I think that a p-value of 1 is reasonable for voxels outside the brain. It's easier to deal with than NaN. That part is related to #253. 

> The "logp_level-voxel_corr-FWE_method-montecarlo" should not contain log-p-values of 0's and the transformation of the map to p-values should not contain p-values of 1's.

For voxels in the mask, I agree. I am just not sure how it's happening. The voxel-level FWE-corrected p-value calculation step (see below) loops through all voxels in the mask and uses `null_to_p()` (which shouldn't allow p-values of 0 or 1 after #353):

https://github.com/neurostuff/NiMARE/blob/c9f0db7a177936acca267db8ec7625c27302a63c/nimare/meta/ale.py#L366-L373

The two possibilities that come to mind are (1) there is a mismatch between the 1D array (`ale_values`) and the mask or (2) I made a mistake in #353 and the p-values were not appropriately clipped.

**NOTE**: I know you specifically said "voxel-level FWE", but a minor thing I want to note for posterity is that the _cluster_-level FWE should have p-values of 1 for voxels outside of the thresholded clusters, rather than just the ones outside the mask.

**Comment by jdkent** [comment]
I think this is from how I was defining "voxels inside the brain", I was using the [MNI mask in resources](https://github.com/neurostuff/NiMARE/blob/c9f0db7a177936acca267db8ec7625c27302a63c/nimare/resources/templates/MNI152_2x2x2_brainmask.nii.gz), not the masker that comes with the meta-analysis result object, are those two masks expected to be different typically when using MNI coordinates?

Anyways, if those masks are expected to be different and the masker from the meta-analysis result object is the one that should be used, then the p-values are being clipped as expected.

**Comment by tsalo** [comment]
The default mask should be that MNI one, but even if they were different the `MetaResults` object _should_ inherit its mask from the `Estimator`, which inherits from the `Dataset` when not specified. Can you provide code to reproduce the issue?

**Comment by jdkent** [comment]
I [made an example on a branch based off the simulation branch](https://github.com/jdkent/NiMARE/blob/93886e086d2268a6313044df60b12b53d82df530/nimare/tests/test_estimator_performance.py#L234), the mask from the masker object is not equivalent to the MNI mask. 30 voxels are removed at some point specifically in this case.

```
def test_mask_issue(simulatedata_cbma, mni_mask):
    _, (_, dataset) = simulatedata_cbma
    fwe = FWECorrector(method="montecarlo", voxel_thresh=ALPHA, n_iters=100, n_cores=N_CORES)
    meta = ale.ALE()
    res = meta.fit(dataset)
    res_mask = res.masker.mask_img
    res_mask_data = res_mask.get_fdata().astype(bool)
    mni_mask_data = mni_mask.get_fdata().astype(bool)

    # this said 30 voxels are different between the two masks
    (res_mask_data != mni_mask_data).sum()

    cres = fwe.transform(res)

    cres_img = cres.get_map("logp_level-voxel_corr-FWE_method-montecarlo", return_type='image')
    cres_arr = cres.get_map("logp_level-voxel_corr-FWE_method-montecarlo", return_type='array')

    mni_cres = cres_img.get_fdata()[mni_mask_data]
    mask_cres = cres_img.get_fdata()[res_mask_data]
    # these two are equivalent
    (cres_arr == mask_cres).all()

    # mni_cres has 30 more entries than mask_cres
    mni_cres.shape != mask_cres.shape
```

**Comment by tsalo** [comment]
Ah, okay, thank you for the code. Since you're specifying the MNI mask separately from the `Dataset` or `Estimator`, it's really all about whether the default `Dataset` mask is the same as the one you specified. I _thought_ it was, but it looks like we use the `nilearn` MNI brain mask instead, which could explain the mismatch:

`Dataset` defaults to `utils.get_template("mni152_2mm", mask="brain")`:
https://github.com/neurostuff/NiMARE/blob/c9f0db7a177936acca267db8ec7625c27302a63c/nimare/dataset.py#L99-L100

Then `utils.get_template()` uses `nilearn.datasets.load_mni152_brain_mask()`:
https://github.com/neurostuff/NiMARE/blob/c9f0db7a177936acca267db8ec7625c27302a63c/nimare/utils.py#L240

We still need to make sure that the original mask doesn't contain any p-values of 1 though.

**Comment by jdkent** [comment]
ah, I think I see my problem, the mni_mask in the repo is indeed different from the one in nilearn, and when using the nilearn mask, no p-values are equal to 1. I think this is resolved, sorry for the noise.

**Comment by jdkent** [comment]
as you've already pointed out, lol.
